default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cdg_coursework_development

test:
  <<: *default
  database: cdg_coursework_test

production:
  <<: *default
  database: cdg_coursework_production
  username: cdg_coursework
  password: <%= ENV['CDG_COURSEWORK_DATABASE_PASSWORD'] %>
